apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo14
  namespace: fleet-local
spec:
  selector:
    matchLabels:
      app: odoo14
      tier: odoo14
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo14
        tier: odoo14
    spec:
      containers:
      - name: odoo14
        env:
          - name: HOST
            value: 10.10.6.163
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
        image: odoo:14.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8069
          name: http
        - containerPort: 8072
          name: longpooling
