apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-odoo-14
  namespace: fleet-local
spec:
  selector:
    matchLabels:
      app: frontend-odoo-14
      tier: frontend-odoo-14
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-odoo-14
        tier: frontend-odoo-14
    spec:
      containers:
      - name: frontend-odoo-14
        image: odoo:14.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8069
          name: /
        - containerPort: 8072
          name: /longpooling
