apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: odoo14
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: odoo-14-test.kmee.dev.br
      http:
        paths:
        - backend:
             serviceName: odoo14
             servicePort: http
          path: /
         pathType: ImplementationSpecific
        - backend:
            serviceName: odoo14
            servicePort: longpooling
          path: /longpooling
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - odoo-14-test.kmee.dev.br
      secretName: letsencrypt-odoo14
status:
  loadBalancer:
    ingress:
    - ip: 10.10.6.11
    - ip: 10.10.6.12
    - ip: 10.10.6.13
