apiVersion: v1
kind: Service
metadata:
  name: frontend-odoo-14
  labels:
    app: odoo-14
    tier: frontend-odoo-14
spec:
  type: NodePort
  ports:
  - name: http
    port: 8069
  - name: longpooling
    port: 8072
  selector:
    app: frontend-odoo-14
    tier: frontend-odoo-14
