apiVersion: v1
kind: Service
metadata:
  name: frontend-odoo-14
  labels:
    app: odoo14
    tier: frontend-odoo-14
spec:
  type: NodePort
  ports:
  - port: 8069
    name: http
  - port: 8072
    name: longpooling
  selector:
    app: odoo14
    tier: frontend-odoo-14
