apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-odoo
  namespace: fleet-local
spec:
  selector:
    matchLabels:
      app: odoo
      tier: frontend-odoo
  replicas: 1
  template:
    metadata:
      labels:
        app: odoo
        tier: frontend-odoo
    spec:
      - env:
        - name: HOST
        value: 10.10.6.163
        - name: PASSWORD
        value: odoo
        - name: USER
        value: odoo
      containers:
      - name: odoo
        image: odoo:14
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8069
        - containerPort: 8072
